import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Login from '../components/Login'
import Footer from '../components/Footer'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Club Management-Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header />
                <div>
                    <Login />
                    <Footer />
                </div>
            </main>

        </div>
    )
}
